# Generated by Django 5.2.4 on 2025-07-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='created_at',
        ),
    ]
